### ISSUE TITLE
Cant assign master to "None" (& Bulk Assign Master Doesn't Work with Rimthreaded)

### ISSUE THREAD

**Issue by maarxx** [cseelhoff/RimThreaded#366]
## [Fluffy's Animal Tab] Bulk Assign Master Doesn't Work with Rimthreaded

![animalsMasterRimthreadedBug](https://user-images.githubusercontent.com/7416299/101951722-773cc700-3bc5-11eb-8b05-3c1ad66a9683.png)

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**

I tested this issue on a fresh game, and was able to replicate it. The "Unassign all" button did not function at all, but I found this to be simply an extension to the more direct issue of not being able to set the master of any animals to "None". This seems to be the root of the issue, and this part happens even when not using "Animal Tabs" mod. This is therefore an issue with vanilla RT.

All the other commands seemed to work though, and I was able to set the masters of animals to "Bonded" through the "Assign to Bonded" command, unlike how the author of this issue portrayed. Although, when testing this issue on my modded play through, I did have one isolated case of not being able to set the master of a particular animal (dragon) to the one they were bonded with, when using the "Assign to bonded" mass command. It still worked when I set the master directly though.

Here is a save illustrating the issue:
[Animal Tab Issue.zip](https://github.com/cseelhoff/RimThreaded/files/6149568/Animal.Tab.Issue.zip)

I did not experience any errors when testing this, but here is the HugsLib log anyway.

https://gist.github.com/HugsLibRecordKeeper/b32d82646a5720d3a2a1f1b1c17fb97c

**Conclusion**
This issue is confirmed, but is rooted in an issue with RT itself. In short, assigning an animal master to "None" does not work.

**Comment by Niilo007** [comment]
tested in 2.0.7
i couldn't assign the animals at all, not in bulk or induvidually

**Comment by cseelhoff** [comment]
Fixed in 2.1.3

**Comment by bababooeyy** [comment]
Issue still occurs for me with 2.1.3 and 2.1.5

**Comment by pastorismylord** [comment]
@cseelhoff issue still persists as per @bababooeyy please advise

**Comment by Niilo007** [comment]
can confirm happens in 2.1.5

**Comment by Niilo007** [comment]
fixed in 2.2.7
