### ISSUE TITLE
"Combat Extended" RimThreaded with Combat Extended: shotgun-likes not working properly

### ISSUE THREAD

**Issue by Awissowo** [cseelhoff/RimThreaded#369]
**Describe the bug**
Various errors appear when you use shotgun-like guns
Info is in screenshots 

**To Reproduce**
1. Select a pawn
2. Equip them with a shotgun and some ammo
3. Draft them
4. Select something to shoot
5. Shoot
6. See errors
     
**Error Log**
https://gist.github.com/c3c7cc37497d34708f60b26d3b4b9551

**Mod List**
-Harmony https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077&searchtext=harmony
-Core
-Royalty
-HugsLib https://steamcommunity.com/sharedfiles/filedetails/?id=818773962&searchtext=hugs+lib
-Mod Manager https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539&searchtext=mod+manager
-RimThreaded https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981&searchtext=rimthreaded
-Combat Extended https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268&searchtext=combat+extended

Load order: https://i.imgur.com/8HQbo7S.png

**Screenshots**
https://i.imgur.com/AJ676rw.png
https://i.imgur.com/PKSg9q8.png
https://i.imgur.com/bNMBiDu.png
https://i.imgur.com/pFPyKQZ.png
https://i.imgur.com/mVRLxKu.png
https://i.imgur.com/uLrja4q.png

**Comment by pastorismylord** [comment]
tested with 2.2.8. Combat Extended seems to be working fine now. No massive logs for explosions anymore

**Comment by pastorismylord** [comment]
shotguns are no longer a problem with combat extended

**Comment by pO0P3R125** [comment]
shotguns are again throwing out exceptions
![RimWorldWin64_bCO2t7eu9I](https://user-images.githubusercontent.com/43865463/123019013-466bf480-d395-11eb-857b-7a1be72e3ab8.jpg)

**Comment by pastorismylord** [comment]
should be fixed now

**Comment by Blitx** [comment]
Error still occurs on 2.5.11. Same steps to reproduce

Error log: https://gist.github.com/HugsLibRecordKeeper/3435e2cd18a6a9ff4d45c154a370b18b
 
Modlist:
Harmony - https://steamcommunity.com/workshop/filedetails/?id=2009463077
HugsLib - https://steamcommunity.com/workshop/filedetails/?id=818773962
Mod Manager - https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539
Combat Extended - https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268
RimThreaded - https://steamcommunity.com/sharedfiles/filedetails/?id=2222907981

Load order:
Harmony
Core
HugsLib
Mod Manager
Combat Extended
RimThreaded

**Comment by Blitx** [comment]
Still an issue on 2.5.15 :(
Same load order and similar error, different coordinates though.
