### ISSUE TITLE
(2.2.13) Changing crop in a growing zone causes pawns to randomly stop sowing

### ISSUE THREAD

**Issue by 15adhami** [cseelhoff/RimThreaded#518]
Changing the crop you are trying to grow in a growing zone will cause the pawns to start sowing in "bursts", where they will sow a few plants, then stop for a few seconds, then sow a few plants again, and repeat. Error messages about WildPlantSpawner occasionally appear. 

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Create new save
2. Create a growing zone
3. Wait for colonists to finish sowing zone
4. Change the crop to some other plant
5. See if pawns randomly go idle or stop sowing, if they don't you might have to try changing the crop again a few times.

**Error Log**
https://gist.github.com/a48769a27e74d7ea3e116d2d50189abf

**Mod list (For vanilla report, it has to be same as below list.)**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* RimThreaded

**Comment by cseelhoff** [comment]
fixed in 2.2.14

**Comment by 15adhami** [comment]
Still happens in 2.2.19. Create a new save file, create a growing zone and set to rice. Wait for pawns to finish sowing, then change it to corn, wait to finish sowing, change to rice, etc. Eventually you will see the pawns go idle and they won't sow.

**Comment by cseelhoff** [comment]
fixed in 2.3.5
